FROM node:16.13-alpine3.14 as build

ENV NODE_ENV production

WORKDIR /app

COPY package.json .

COPY yarn.lock .

RUN yarn install --production

COPY . .

RUN yarn build



FROM nginx:1.21.0-alpine as production

COPY --from=build /app/build /usr/share/nginx/html

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]