POST http://localhost:8080/private/set_tinkoff
content-type: application/json

{
  "figi":"BBG004S68829"
}

###

POST http://localhost:8080/private/tinkoff/personal_stocks

###

POST http://localhost:8080/private/tinkoff/last_candle
content-type: application/json

{
  "figi":"BBG004S68829"
}