POST http://localhost:8080/users
content-type: application/json

{
    "email":"user@gmail.com",
    "password":"password"
}

###

POST http://localhost:8080/users
content-type: application/json

{
    "email":"invalid",
    "password":"password"
}

###

POST http://localhost:8080/users
content-type: application/json

{
    "email":"user@gmail.com"
}

###

POST http://localhost:8080/sessions
content-type: application/json

{
    "email":"user@gmail.com",
    "password":"123"
}

###

POST http://localhost:8080/sessions
content-type: application/json

{
    "email":"user@gmail.com",
    "password":"password"
}

###

GET http://localhost:8080/private/whoami

###

OPTIONS http://localhost:8080/sessions

###

POST http://localhost:8080/private/set_tinkoff

{
    "tinkoffapikey":"t.zi-GzKc-R6kOQF3MqGFBCSCSKX-B4aed_OwhJbjqQZCL9va5cPlmiMRNRfCDMW2_cB7RhSylrxHLvX_AOlW10g"
}